variable "region"          { type = string  default = "eu-central-1" }
variable "project"         { type = string  default = "hristo-rusev" }
variable "vpc_cidr"        { type = string  default = "10.0.0.0/16" }
variable "public_subnets"  { type = list(string) default = ["10.0.0.0/24","10.0.1.0/24"] }
variable "private_subnets" { type = list(string) default = ["10.0.10.0/24","10.0.11.0/24"] }
variable "instance_type"   { type = string  default = "t3.micro" }
variable "db_name"         { type = string  default = "appdb" }
variable "db_username"     { type = string  default = "appadmin" }
variable "db_password"     { type = string  sensitive = true }